title: Brian David Hall
author: Brian David Hall
url: https://briandavidhall.com # root address of the site
description: > # description of the site (multiple lines allowed)

permalink: /:slug/
include: ['_pages']
markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:path/

icon: "./favicon.ico"

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-target-blank
  - jekyll-sitemap

