# Site settings
title: Brian David Hall
author: Brian David Hall
url: https://briandavidhall.com # root address of the site
baseurl: "" # the subpath of your site, e.g. /blog
icon: /assets/images/favicon.ico
author: Brian David Hall
permalink: /:title/

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/page/:num/"
hide_search: true
hide_credits: true
